# Generated by Django 5.0.7 on 2024-07-24 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_player_remove_room_host_remove_room_topic_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team_name',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='player',
            name='number',
            field=models.BigIntegerField(),
        ),
    ]
