# Generated by Django 5.0.7 on 2024-07-24 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_team'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='team_player',
        ),
    ]
