# Generated by Django 5.0.7 on 2024-07-27 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_score_board'),
    ]

    operations = [
        migrations.RenameField(
            model_name='score_board',
            old_name='Points',
            new_name='points',
        ),
    ]
